<?xml version="1.0" encoding="UTF-8"?><testrun name="java" project="gerenciadorApi" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.cjhsoftware.gerenciadorApi.GerenciadorApiApplicationTests" time="0.887" displayname="GerenciadorApiApplicationTests" uniqueid="[engine:junit-jupiter]/[class:com.cjhsoftware.gerenciadorApi.GerenciadorApiApplicationTests]">
    <testcase name="contextLoads" classname="com.cjhsoftware.gerenciadorApi.GerenciadorApiApplicationTests" time="0.887" displayname="contextLoads()" uniqueid="[engine:junit-jupiter]/[class:com.cjhsoftware.gerenciadorApi.GerenciadorApiApplicationTests]/[method:contextLoads()]"/>
  </testsuite>
  <testsuite name="com.cjhsoftware.gerenciadorApi.domain.repository.ProjetoRepositoryTest" time="0.554" displayname="ProjetoRepositoryTest" uniqueid="[engine:junit-jupiter]/[class:com.cjhsoftware.gerenciadorApi.domain.repository.ProjetoRepositoryTest]">
    <testcase name="SalvaNoBDcomSucesso" classname="com.cjhsoftware.gerenciadorApi.domain.repository.ProjetoRepositoryTest" time="0.554" displayname="Usa o repositorio para salvar uma entidade de Projeto no banco de dados" uniqueid="[engine:junit-jupiter]/[class:com.cjhsoftware.gerenciadorApi.domain.repository.ProjetoRepositoryTest]/[method:SalvaNoBDcomSucesso()]">
      <failure>
        <expected>2</expected>
        <actual>1</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;2&gt; but was: &lt;1&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:632)&#13;
	at com.cjhsoftware.gerenciadorApi.domain.repository.ProjetoRepositoryTest.SalvaNoBDcomSucesso(ProjetoRepositoryTest.java:36)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
